### ISSUE TITLE
部分曲池重复，以及原创希c位技能问题

### ISSUE THREAD

**Issue by kaigu1997** [Glaceon31/LLhelper#22]
![20200530022211](https://user-images.githubusercontent.com/22344426/83321292-97ee9200-a21c-11ea-82a4-465b587a784d.png)
樱花再见ex出现了两遍（多打了个1的手残？）
![20200530022512](https://user-images.githubusercontent.com/22344426/83321325-dc7a2d80-a21c-11ea-9ffc-01de8a905ecf.png)
![QQ截图20200530022703](https://user-images.githubusercontent.com/22344426/83321363-121f1680-a21d-11ea-8742-6738fe61d7c7.jpg)
国服原创希的主唱技能有问题，计算的属性是NAN（测试曲目为届星ex）

**Comment by ben1222** [comment]
关于重复谱面的问题: 1119 号是普通歌曲中的那个, 11119 号是传统活动(告别毕业)中的随机谱... 随机谱的表达方式在不断改变... 等以后稳定了再看吧...
国服原创卡牌的主唱技能: 已修复
